# Generated by Django 3.2.7 on 2021-10-04 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_instrument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='symbol',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.trade'),
        ),
    ]
