# Generated by Django 3.2.7 on 2021-10-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_auto_20211004_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
