# Generated by Django 3.2.7 on 2021-10-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0005_delete_instrument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='date',
        ),
    ]
